changelog:
  exclude:
    labels:
      - dependencies
    authors:
      - dependabot
  categories:
    - title: Breaking Changes
      labels:
        - breaking change
    - title: New Features
      labels:
        - "type: feature"
        - "type: enhancement"
    - title: Bug Fixes
      labels:
        - "type: bug"
    - title: Documentation
      labels:
        - "type: documentation"
    - title: Other Changes
      labels:
        - "*"
